name: Android

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          maven-version: '3.8.8'

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev

      - name: Gluon Build
        run: |
          export ANDROID_SDK=$ANDROID_HOME
          mvn -Pandroid gluonfx:build gluonfx:package


      - name: Make staging directory
        run: mkdir staging

      - name: Copy packages to staging
        run: cp -r target/gluonfx/aarch64-android/gvm/BeeAware.* staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging