name: iOS

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          maven-version: '3.8.8'

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - uses: Apple-Actions/import-codesign-certs@v1
#        with:
#          p12-file-base64: ${{ secrets.GLUON_IOS_CERTIFICATES_FILE_BASE64 }}
#          p12-password: ${{ secrets.GLUON_IOS_CERTIFICATES_PASSWORD }}

#      - uses: Apple-Actions/download-provisioning-profiles@v1
#        with:
#          bundle-id: com.beeaware.BeeAwareApp
#          issuer-id: ${{ secrets.GLUON_IOS_APPSTORE_ISSUER_ID }}
#          api-key-id: ${{ secrets.GLUON_IOS_APPSTORE_KEY_ID }}
#          api-private-key: ${{ secrets.GLUON_IOS_APPSTORE_PRIVATE_KEY }}

      - name: Gluon Build
        run: mvn -Pios gluonfx:build gluonfx:package

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging

#      - uses: Apple-Actions/upload-testflight-build@master
#        with:
#          app-path: target/gluonfx/arm64-ios/BeeAware.ipa
#          issuer-id: ${{ secrets.GLUON_IOS_APPSTORE_ISSUER_ID }}
#          api-key-id: ${{ secrets.GLUON_IOS_APPSTORE_KEY_ID }}
#          api-private-key: ${{ secrets.GLUON_IOS_APPSTORE_PRIVATE_KEY }}